
package it.istruzione.poninchiaro.bean.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "nusoap_autPortType", targetNamespace = "urn:nusoap_aut")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NusoapAutPortType {


    /**
     * Restituisce documenti e immagini
     * 
     * @param parameters
     * @return
     *     returns it.istruzione.poninchiaro.bean.ws.GetdocsResponseType
     */
    @WebMethod(action = "http://pon20142020.indire.it/wsdl/inviaponinchiaro.php/getdocs")
    @WebResult(name = "getdocsResponse", targetNamespace = "urn:nusoap_aut", partName = "parameters")
    public GetdocsResponseType getdocs(
        @WebParam(name = "getdocs", targetNamespace = "urn:nusoap_aut", partName = "parameters")
        GetdocsRequestType parameters);

}
