
package it.istruzione.poninchiaro.bean.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "nusoap_aut", targetNamespace = "urn:nusoap_aut", wsdlLocation = "file:/C:/Users/slfpicci/workspaceMobilita/poninchiaro/src/main/webapp/WEB-INF/wsdl/inviaponinchiaro.wsdl")
public class NusoapAut
    extends Service
{

    private final static URL NUSOAPAUT_WSDL_LOCATION;
    private final static WebServiceException NUSOAPAUT_EXCEPTION;
    private final static QName NUSOAPAUT_QNAME = new QName("urn:nusoap_aut", "nusoap_aut");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/slfpicci/workspaceMobilita/poninchiaro/src/main/webapp/WEB-INF/wsdl/inviaponinchiaro.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUSOAPAUT_WSDL_LOCATION = url;
        NUSOAPAUT_EXCEPTION = e;
    }

    public NusoapAut() {
        super(__getWsdlLocation(), NUSOAPAUT_QNAME);
    }

    public NusoapAut(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUSOAPAUT_QNAME, features);
    }

    public NusoapAut(URL wsdlLocation) {
        super(wsdlLocation, NUSOAPAUT_QNAME);
    }

    public NusoapAut(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUSOAPAUT_QNAME, features);
    }

    public NusoapAut(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NusoapAut(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NusoapAutPortType
     */
    @WebEndpoint(name = "nusoap_autPort")
    public NusoapAutPortType getNusoapAutPort() {
        return super.getPort(new QName("urn:nusoap_aut", "nusoap_autPort"), NusoapAutPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NusoapAutPortType
     */
    @WebEndpoint(name = "nusoap_autPort")
    public NusoapAutPortType getNusoapAutPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:nusoap_aut", "nusoap_autPort"), NusoapAutPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUSOAPAUT_EXCEPTION!= null) {
            throw NUSOAPAUT_EXCEPTION;
        }
        return NUSOAPAUT_WSDL_LOCATION;
    }

}
